[build]
builder = "nixpacks"

[deploy]
restartPolicyCondition = "on-failure"
restartPolicyMaxRetries = 5

[[services]]
name = "backend"
cmd = "cd backend && npm run start"
buildCmd = "cd backend && npm install && npm run build"

[[envVars]]
name = "NODE_ENV"
value = "production"

[[envVars]]
name = "PORT"
value = "8000"
